# Generated by Django 6.0.6 on 2026-06-04 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('policy_accepted', models.BooleanField(default=False, verbose_name='Соглашение принято')),
                ('survey_completed', models.BooleanField(default=False, verbose_name='Опрос пройден')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Баланс, ₽')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='accounts.userprofile', verbose_name='Кто пригласил')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
