# Generated by Django 6.0.6 on 2026-06-04 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.CharField(max_length=40, verbose_name='Введённый код')),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('invalid', 'Неверный'), ('used', 'Уже использован')], max_length=10, verbose_name='Статус')),
                ('reward', models.PositiveIntegerField(default=0, verbose_name='Начислено, ₽')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_entries', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Запись кода',
                'verbose_name_plural': 'История кодов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Код')),
                ('reward', models.PositiveIntegerField(default=10, verbose_name='Награда, ₽')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда активирован')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_codes', to='accounts.userprofile', verbose_name='Активировал')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
