# Generated by Django 6.0.6 on 2026-06-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeentry',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('lose', 'Не выигрыш'), ('invalid', 'Неверный'), ('used', 'Уже использован')], max_length=10, verbose_name='Статус'),
        ),
    ]
