# Generated by Django 6.0.6 on 2026-06-04 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, verbose_name='Картинка')),
                ('prize_type', models.CharField(choices=[('combo', 'Комбо'), ('set', 'Сет'), ('cash', 'Денежный'), ('merch', 'Мерч')], default='merch', max_length=10, verbose_name='Тип')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главный приз')),
            ],
            options={
                'verbose_name': 'Приз',
                'verbose_name_plural': 'Призы',
            },
        ),
        migrations.CreateModel(
            name='UserPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('won', 'Выигран'), ('pending', 'Ожидает'), ('purchased', 'Куплен')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prizes.prize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prizes', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Приз пользователя',
                'verbose_name_plural': 'Призы пользователей',
            },
        ),
    ]
