# Generated by Django 6.0.6 on 2026-06-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprize',
            name='status',
            field=models.CharField(choices=[('won', 'Выигран'), ('pending', 'Ожидает')], default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
