# Generated by Django 6.0.6 on 2026-06-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0002_alter_userprize_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='win_chance',
            field=models.PositiveIntegerField(default=0, help_text='Вероятность, что код выиграет именно этот приз (в розыгрыше). 0 = не разыгрывается.', verbose_name='Шанс выигрыша, %'),
        ),
    ]
