# Generated by Django 6.0.6 on 2026-06-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('processing', 'Оформлен'), ('shipping', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='processing', max_length=12, verbose_name='Статус заказа'),
        ),
    ]
