# Generated by Django 6.0.6 on 2026-06-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_purchase_options_purchase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('assembling', 'Собирается'), ('shipping', 'В пути'), ('arrived', 'Приехал'), ('handed', 'Выдан покупателю'), ('cancelled', 'Отменён')], default='assembling', max_length=12, verbose_name='Статус заказа'),
        ),
    ]
