# Generated by Django 6.0.6 on 2026-06-05 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.surveyoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.surveyquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Ответ опроса',
                'verbose_name_plural': 'Ответы опроса',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
