# Generated by Django 6.0.6 on 2026-06-11 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('home', '0002_surveyanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raffle',
            options={'ordering': ['draw_at'], 'verbose_name': 'Розыгрыш', 'verbose_name_plural': 'Розыгрыши'},
        ),
        migrations.AddField(
            model_name='raffle',
            name='drawn_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда проведён'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_raffles', to='accounts.userprofile', verbose_name='Победитель'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winning_code',
            field=models.CharField(blank=True, max_length=40, verbose_name='Выигравший код'),
        ),
    ]
