# Generated by Django 6.0.6 on 2026-06-11 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('home', '0003_alter_raffle_options_raffle_drawn_at_raffle_winner_and_more'),
        ('prizes', '0003_prize_win_chance'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleWin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.CharField(max_length=40, verbose_name='Выигравший код')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prizes.prize')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='home.raffle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_wins', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Выигрыш розыгрыша',
                'verbose_name_plural': 'Выигрыши розыгрышей',
            },
        ),
    ]
